# Generated by Django 6.0.3 on 2026-03-19 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre de la cuenta (ej: 'Bancolombia Ahorros', 'Nequi')", max_length=100)),
                ('account_type', models.CharField(choices=[('BANK', 'Cuenta Bancaria'), ('WALLET', 'Billetera Digital'), ('CREDIT_CARD', 'Tarjeta de Crédito'), ('CASH', 'Efectivo')], max_length=20)),
                ('currency', models.CharField(choices=[('COP', 'Peso Colombiano'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro')], default='COP', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Balance actual de la cuenta', max_digits=15)),
                ('color', models.CharField(default='#4F46E5', help_text="Color en formato hex (ej: '#4F46E5')", max_length=7)),
                ('icon', models.CharField(default='wallet', help_text="Nombre del ícono (ej: 'wallet', 'bank', 'credit-card')", max_length=50)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Cupo total de la tarjeta de crédito', max_digits=15, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de interés mensual (%)', max_digits=5, null=True)),
                ('cut_off_day', models.PositiveSmallIntegerField(blank=True, help_text='Día de corte de la tarjeta (1-31)', null=True)),
                ('payment_day', models.PositiveSmallIntegerField(blank=True, help_text='Día límite de pago (1-31)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'db_table': 'accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
