# Generated by Django 6.0.3 on 2026-03-20 02:25
"""
📚 DATA MIGRATION — Inserta las categorías del sistema.

A diferencia de una migración normal (que cambia la estructura de la BD),
esta inserta DATOS iniciales. Se ejecuta una sola vez al correr `migrate`.

RunPython recibe dos funciones:
- forward: lo que se ejecuta al migrar (insertar categorías)
- reverse: lo que se ejecuta al revertir (borrar categorías)
"""

from django.db import migrations


# 📚 Estas son las categorías que vienen con la app.
# Formato: (nombre, tipo, ícono, color)
DEFAULT_CATEGORIES = [
    # ── Gastos ──
    ("Comida", "EXPENSE", "utensils", "#EF4444"),
    ("Transporte", "EXPENSE", "car", "#F97316"),
    ("Vivienda", "EXPENSE", "home", "#8B5CF6"),
    ("Servicios", "EXPENSE", "zap", "#EAB308"),
    ("Salud", "EXPENSE", "heart-pulse", "#EC4899"),
    ("Educación", "EXPENSE", "graduation-cap", "#6366F1"),
    ("Entretenimiento", "EXPENSE", "gamepad-2", "#14B8A6"),
    ("Ropa", "EXPENSE", "shirt", "#F43F5E"),
    ("Supermercado", "EXPENSE", "shopping-cart", "#22C55E"),
    ("Restaurantes", "EXPENSE", "coffee", "#A855F7"),
    ("Suscripciones", "EXPENSE", "repeat", "#0EA5E9"),
    ("Mascotas", "EXPENSE", "paw-print", "#D946EF"),
    ("Regalos", "EXPENSE", "gift", "#F59E0B"),
    ("Otros gastos", "EXPENSE", "more-horizontal", "#6B7280"),
    # ── Ingresos ──
    ("Salario", "INCOME", "banknote", "#10B981"),
    ("Freelance", "INCOME", "laptop", "#3B82F6"),
    ("Inversiones", "INCOME", "trending-up", "#8B5CF6"),
    ("Ventas", "INCOME", "tag", "#F97316"),
    ("Reembolsos", "INCOME", "rotate-ccw", "#06B6D4"),
    ("Otros ingresos", "INCOME", "more-horizontal", "#6B7280"),
]


def seed_categories(apps, schema_editor):
    """📚 Forward: inserta las categorías del sistema."""
    Category = apps.get_model("categories", "Category")
    categories = [
        Category(
            name=name,
            category_type=category_type,
            icon=icon,
            color=color,
            is_default=True,
            user=None,
        )
        for name, category_type, icon, color in DEFAULT_CATEGORIES
    ]
    Category.objects.bulk_create(categories)


def remove_categories(apps, schema_editor):
    """📚 Reverse: borra las categorías del sistema (para revertir la migración)."""
    Category = apps.get_model("categories", "Category")
    Category.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
